services:
  nginx:
    image: nginx:1.28-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - spring-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/cert:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot

  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/data:/var/lib/mysql

  spring-app:
    image: ${DOCKERHUB_USERNAME}/inchelin:latest
    container_name: inchelin-app
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CONTEXT_PATH=${CONTEXT_PATH}
    depends_on:
      - mariadb