services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - spring-app

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/data:/var/lib/mysql

  spring-app:
#    build: .
    image: ${DOCKERHUB_USERNAME}/inchelin:latest
    container_name: inchelin-app
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=${DB_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CONTEXT_PATH=${CONTEXT_PATH}
    depends_on:
      - mariadb